site_name: Ky≈çkai Tansa docs
site_url: https://arturh85.github.io/anki-taiso/docs/
use_directory_urls: true
theme:
  name: readthedocs
extra_css:
  - mkdocs.css
plugins:
  - search
  - mermaid2
  - awesome-pages
  - puml-file
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
nav:
  - "Home": index.md
  - ... | tutorial/*.md
  - ... | howto/*.md
  - ... | explanation/*.md
  - ... | reference/*.md
  - "Links":
    - "Git Project": "https://github.com/arturh85/anki-taiso"
